source 'https://rubygems.org'
gem 'jekyll', '~> 4.3.4'
gem 'activesupport', '~> 7.0'
gem 'classifier-reborn', '~> 2.3.0'
gem 'jekyll-archives', '~> 2.2.1'
gem 'jekyll-email-protect', '~> 1.1.0'
gem 'jekyll-get-json', '~> 1.0.0'
gem 'jekyll-imagemagick', '~> 1.4.0'
gem 'jekyll-jupyter-notebook', '~> 0.0.6'
gem 'jekyll-link-attributes', '~> 1.0.1'
gem 'jekyll-minifier', '~> 0.1.10'
gem 'jekyll-paginate-v2', '~> 3.0.0'
gem 'jekyll-regex-replace', '~> 1.1.0'
gem 'jekyll-scholar', '~> 7.1.3'
gem 'jekyll-tabs', '~> 1.2.1'
gem 'jekyll-toc', '~> 0.19.0'
gem 'jekyll-twitter-plugin', '~> 2.1.0'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'toc'
gem 'jekyll-sass-converter', '~> 3.0'
gem 'sassc', '~> 2.4'
gem 'css_parser'
gem 'feedjira'
gem 'httparty'
