name: Build and Deploy Jekyll Site

on:
  push:
    branches: ["master"]  # Replace with your default branch if different
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Install Ruby Dependencies
        run: bundle install

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Jupyter
        run: |
          pip install --user jupyter
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build Jekyll Site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
